Repository Ahzem/Seyoni, pull requests merged in 2024-10, with the labels that each got.

#82 Develop a new Menu page based on the provided Figma prototype.
  Back-End/app.js
  Back-End/controllers/seekerController.js
  Back-End/controllers/userController.js
  Back-End/index.js
  Back-End/models/otpModel.js
  Back-End/models/userModel.js
  Back-End/package-lock.json
  Back-End/package.json
  Back-End/routes/seekerRoutes.js
  Back-End/routes/userRoutes.js
  Back-End/services/otpService.js
  Front-End/assets/icons/forms/AddBookmark.png
  Front-End/assets/icons/forms/AddRecord.png
  Front-End/assets/icons/forms/Call.png
  Front-End/assets/icons/forms/ChatBubble.png
  Front-End/assets/icons/forms/Clock.png
  Front-End/assets/icons/forms/Description.png
  Front-End/assets/icons/forms/Edit.png
  Front-End/assets/icons/forms/EditCalendar.png
  Front-End/assets/icons/forms/ImageFileAdd.png
  Front-End/assets/icons/forms/PlaceMarker.png
  Front-End/assets/icons/forms/Profile.png
  Front-End/assets/icons/menu/Bookmark.png
  Front-End/assets/icons/menu/Contact.png
  Front-End/assets/icons/menu/CreditCard.png
  Front-End/assets/icons/menu/Edit Account.png
  Front-End/assets/icons/menu/FAQ.png
  Front-End/assets/icons/menu/FastCart.png
  Front-End/assets/icons/menu/HomeAddress.png
  Front-End/assets/icons/menu/Info.png
  Front-End/assets/icons/menu/Invite.png
  Front-End/assets/icons/menu/Key.png
  Front-End/assets/icons/menu/Logout.png
  Front-End/assets/icons/menu/MarkerB.png
  Front-End/assets/icons/menu/Privacy.png
  Front-End/assets/icons/menu/Settings.png
  Front-End/assets/icons/menu/Siren.png
  Front-End/assets/icons/menu/Terms.png
  Front-End/assets/icons/menu/Translator.png
  Front-End/assets/icons/menu/User.png
  Front-End/flutter_01.png
  Front-End/lib/src/api/register_seeker.dart
  Front-End/lib/src/config/route.dart
  Front-End/lib/src/config/url.dart
  Front-End/lib/src/constants/constants_font.dart
  Front-End/lib/src/pages/auth/forgot-password/verify_code_page.dart
  Front-End/lib/src/pages/auth/otp/otp_screen.dart
  Front-End/lib/src/pages/main/mainpage.dart
  Front-End/lib/src/pages/menu/components/menu_item.dart
  Front-End/lib/src/pages/menu/menupage.dart
  Front-End/lib/src/pages/sign-pages/signup_page.dart
  Front-End/lib/src/services/auth
  Front-End/lib/src/widgets/alertbox/menu.dart
  Front-End/lib/src/widgets/alertbox/verification_success.dart
  Front-End/lib/src/widgets/custom_appbar.dart
  Front-End/pubspec.yaml
Labels: Hacktoberfest

#84 The profile page of provider from seeker's view
  Back-End/controllers/index.js
  Back-End/controllers/seeker/resendOtp.js
  Back-End/controllers/seeker/signInSeeker.js
  Back-End/controllers/seeker/signOutSeeker.js
  Back-End/controllers/seeker/signUpSeeker.js
  Back-End/controllers/seeker/verifySignUpOtp.js
  Back-End/controllers/seekerController.js
  Back-End/routes/seekerRoutes.js
  Front-End/assets/images/plumbering-1.jpg
  Front-End/assets/images/plumbering-2.jpg
  Front-End/assets/images/plumbering-3.jpg
  Front-End/assets/images/plumbering-4.jpg
  Front-End/assets/images/plumbering-5.jpg
  Front-End/assets/images/plumbering-6.jpg
  Front-End/assets/images/profile-1.jpg
  Front-End/assets/images/profile-2.jpg
  Front-End/assets/images/profile-3.jpg
  Front-End/assets/images/profile-4.jpg
  Front-End/assets/images/profile-5.jpg
  Front-End/assets/images/profile-6.jpg
  Front-End/assets/images/profile-7.jpg
  Front-End/lib/src/config/url.dart
  Front-End/lib/src/constants/constants_font.dart
  Front-End/lib/src/pages/auth/forgot-password/verify_code_page.dart
  Front-End/lib/src/pages/auth/otp/otp_screen.dart
  Front-End/lib/src/pages/categories/categories.dart
  Front-End/lib/src/pages/home/home.dart
  Front-End/lib/src/pages/main/mainpage.dart
  Front-End/lib/src/pages/menu/components/menu_item.dart
  Front-End/lib/src/pages/profiles/provider/components/badge_widget.dart
  Front-End/lib/src/pages/profiles/provider/components/full_screen_image.dart
  Front-End/lib/src/pages/profiles/provider/components/icon_button_widget.dart
  Front-End/lib/src/pages/profiles/provider/components/image_paths.dart
  Front-End/lib/src/pages/profiles/provider/components/profile_avatar.dart
  Front-End/lib/src/pages/profiles/provider/components/stat_widget.dart
  Front-End/lib/src/pages/profiles/provider/provider_profile.dart
  Front-End/lib/src/pages/profiles/provider/seeker_view.dart
  Front-End/lib/src/pages/profiles/seeker/provider_view.dart
  Front-End/lib/src/pages/profiles/seeker/seeker_profile.dart
  Front-End/lib/src/services/auth
  Front-End/lib/src/services/auth.dart
  Front-End/lib/src/widgets/alertbox/menu.dart
  Front-End/lib/src/widgets/custom_button.dart
Labels: Hacktoberfest

#86 Chat page successfully created
  Back-End/chat/index.js
  Back-End/package-lock.json
  Docs/presentations/Project Proposel Presentation.pptx
  Front-End/lib/src/pages/chat/chat_page.dart
  Front-End/lib/src/pages/main/mainpage.dart
  Front-End/lib/src/pages/profiles/provider/components/stat_widget.dart
  Front-End/pubspec.lock
  Front-End/pubspec.yaml
Labels: Hacktoberfest

#95 Forms
  Front-End/android/app/src/main/AndroidManifest.xml
  Front-End/ios/Runner/Info.plist
  Front-End/lib/src/pages/auth/forgot-password/forgot_password_page.dart
  Front-End/lib/src/pages/forms/components/buttons.dart
  Front-End/lib/src/pages/forms/components/date_picker.dart
  Front-End/lib/src/pages/forms/components/google_map_widget.dart
  Front-End/lib/src/pages/forms/components/image_picker.dart
  Front-End/lib/src/pages/forms/components/record_field.dart
  Front-End/lib/src/pages/forms/components/service_provider_info.dart
  Front-End/lib/src/pages/forms/components/text_field.dart
  Front-End/lib/src/pages/forms/components/time_picker.dart
  Front-End/lib/src/pages/forms/hiring_form.dart
  Front-End/lib/src/pages/main/mainpage.dart
  Front-End/lib/src/widgets/custom_button.dart
  Front-End/macos/Flutter/GeneratedPluginRegistrant.swift
  Front-End/pubspec.lock
  Front-End/pubspec.yaml
Labels: enhancement, Hacktoberfest

#96 Refactor form buttons and add form components
  Front-End/lib/src/pages/forms/components/buttons.dart
  Front-End/lib/src/pages/forms/hiring_form.dart
  Front-End/lib/src/widgets/alertbox/reservation_confirmation.dart
  Front-End/lib/src/widgets/alertbox/unsaved_changes.dart
Labels: enhancement, Hacktoberfest

#97 designed and created catogarized menu features
  Front-End/assets/icons/menu/Business.png
  Front-End/assets/icons/menu/Delete.png
  Front-End/assets/icons/menu/Home.png
  Front-End/assets/icons/menu/Notification.png
  Front-End/assets/icons/menu/Payment_History.png
  Front-End/assets/icons/menu/Star.png
  Front-End/assets/icons/menu/about_us.png
  Front-End/assets/icons/menu/add_friends.png
  Front-End/assets/icons/menu/add_payment.png
  Front-End/assets/icons/menu/authentication.png
  Front-End/assets/icons/menu/d_location.png
  Front-End/assets/icons/menu/faq1.png
  Front-End/assets/icons/menu/feedback.png
  Front-End/assets/icons/menu/history.png
  Front-End/assets/icons/menu/live_chat.png
  Front-End/assets/icons/menu/manage_payment.png
  Front-End/assets/icons/menu/privacy_policy.png
  Front-End/assets/icons/menu/reward.png
  Front-End/assets/icons/menu/saved_location.png
  Front-End/assets/icons/menu/t&c.png
  Front-End/lib/src/pages/menu/menupage.dart
Labels: Hacktoberfest

#104 The Hiring workflow completed
  Back-End/app.js
  Back-End/controllers/providerController.js
  Back-End/models/providerModel.js
  Back-End/models/reservation.js
  Back-End/routes/providerRoutes.js
  Back-End/uploadProviders.js
  Front-End/assets/icons/Category/Technician.png
  Front-End/lib/src/pages/category/category_page.dart
  Front-End/lib/src/pages/category/components/categories.dart
  Front-End/lib/src/pages/category/components/cities.dart
  Front-End/lib/src/pages/category/components/subcategories.dart
  Front-End/lib/src/pages/category/subcategory_page.dart
  Front-End/lib/src/pages/forms/components/service_provider_info.dart
  Front-End/lib/src/pages/forms/hiring_form.dart
  Front-End/lib/src/pages/forms/order_view.dart
  Front-End/lib/src/pages/location/select_location_page.dart
  Front-End/lib/src/pages/main/mainpage.dart
  Front-End/lib/src/pages/profiles/provider/components/full_screen_image.dart
  Front-End/lib/src/pages/profiles/provider/seeker_view.dart
  Front-End/lib/src/pages/providers-list/components/provider_card.dart
  Front-End/lib/src/pages/providers-list/components/provider_data_notifier.dart
  Front-End/lib/src/pages/providers-list/list_of_providers.dart
  Front-End/pubspec.lock
  Front-End/pubspec.yaml
  pubspec.yaml
Labels: enhancement, Hacktoberfest

#105 category page restructured with new icons
  Front-End/assets/icons/Category/appliance.png
  Front-End/assets/icons/Category/fan.png
  Front-End/assets/icons/Category/gutter.png
  Front-End/assets/icons/Category/mechanic.png
  Front-End/lib/src/pages/category/components/categories.dart
Labels: Hacktoberfest

#111 Refactor validation logic by creating a Validators utility class; upd…
  Front-End/lib/src/pages/provider/login/provider_signin_page.dart
  Front-End/lib/src/pages/provider/registration/provider_registration_page.dart
  Front-End/lib/src/utils/validators.dart
Labels: enhancement

#112 Provider registration and log in process backend completed
  Back-End/app.js
  Back-End/controllers/providerController.js
  Back-End/models/providerModel.js
  Back-End/routes/providerRoutes.js
  Front-End/lib/src/config/url.dart
  Front-End/lib/src/pages/provider/components/custom_text_field.dart
  Front-End/lib/src/pages/provider/components/location_field.dart
  Front-End/lib/src/pages/provider/home/provider_home_page.dart
  Front-End/lib/src/pages/provider/login/provider_signin_page.dart
  Front-End/lib/src/pages/provider/registration/provider_registration_page.dart
  Front-End/lib/src/pages/seeker/category/category_page.dart
  Front-End/lib/src/pages/seeker/forms/components/service_provider_info.dart
  Front-End/lib/src/pages/seeker/forms/hiring_form.dart
  Front-End/lib/src/pages/seeker/main/mainpage.dart
  Front-End/lib/src/pages/seeker/order-history/components/history_card.dart
  Front-End/lib/src/pages/seeker/profiles/components/profile_avatar.dart
  Front-End/lib/src/pages/seeker/profiles/provider_in_seeker_view.dart
  Front-End/lib/src/pages/seeker/providers-list/components/provider_card.dart
  Front-End/lib/src/pages/seeker/providers-list/list_of_providers.dart
  Front-End/lib/src/pages/seeker/sign-pages/components/fields/email.dart
  Front-End/lib/src/pages/seeker/sign-pages/components/fields/new_pw.dart
  Front-End/lib/src/pages/seeker/sign-pages/components/fields/password.dart
  Front-End/lib/src/pages/seeker/sign-pages/components/fields/phone_num.dart
  Front-End/lib/src/services/location_service.dart
Labels: enhancement, Hacktoberfest

#113 Feat/pro/2
  Back-End/app.js
  Back-End/controllers/providerController.js
  Back-End/controllers/reservationController.js
  Back-End/middleware/authMiddleware.js
  Back-End/models/reservation.js
  Back-End/routes/providerRoutes.js
  Back-End/routes/reservationRoutes.js
  Front-End/android/app/build.gradle
  Front-End/android/build.gradle
  Front-End/lib/main.dart
  Front-End/lib/src/api/login_seeker.dart
  Front-End/lib/src/api/register_seeker.dart
  Front-End/lib/src/config/route.dart
  Front-End/lib/src/config/url.dart
  Front-End/lib/src/pages/admin/admin_home_page.dart
  Front-End/lib/src/pages/provider/home/provider_home_page.dart
  Front-End/lib/src/pages/provider/home/reservation_detail_page.dart
  Front-End/lib/src/pages/provider/login/provider_signin_page.dart
  Front-End/lib/src/pages/provider/registration/provider_registration_page.dart
  Front-End/lib/src/pages/seeker/forms/components/google_map_widget.dart
  Front-End/lib/src/pages/seeker/forms/components/text_field.dart
  Front-End/lib/src/pages/seeker/forms/hiring_form.dart
  Front-End/lib/src/pages/seeker/forms/order_view.dart
  Front-End/lib/src/pages/seeker/order-history/components/history_card.dart
  Front-End/lib/src/pages/seeker/order-history/order_history_page.dart
  Front-End/lib/src/pages/seeker/profiles/provider_in_seeker_view.dart
  Front-End/lib/src/pages/seeker/providers-list/components/provider_card.dart
  Front-End/lib/src/pages/seeker/providers-list/list_of_providers.dart
  Front-End/lib/src/widgets/custom_button.dart
Labels: enhancement
